### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by marcheimendinger** [catamphetamine/react-time-ago#10]
Hello,

Amazing package, thanks !

Just a question… in VS Code I have an error saying the package is missing a declaration file.
I tried `npm install @types/react-time-ago` without luck. It's the only package where I have this error.

Any reason for that ?

**Comment by catamphetamine** [comment]
Hi.
This package doesn't have TypeScript typings.

**Comment by marcheimendinger** [comment]
Ok, thanks. Any plan to add TypeScript typings support ?

**Comment by catamphetamine** [comment]
No, I don’t use it.

**Comment by joshtronic** [comment]
> Hello,
> 
> Amazing package, thanks !
> 
> Just a question… in VS Code I have an error saying the package is missing a declaration file.
> I tried `npm install @types/react-time-ago` without luck. It's the only package where I have this error.
> 
> Any reason for that ?

in case you haven't run into it yet, https://www.npmjs.com/package/react-timeago does have bindings and is nearly identical (aside from the twitter type needing to be implemented manually, but that's easy enough to lift from the the original package)

**Comment by catamphetamine** [comment]
Added TypeScript "typings" in `react-time-ago@7.1.2`.
