### ISSUE TITLE
Need Working Example Code

### ISSUE THREAD

**Issue by Awaisqr** [catamphetamine/react-time-ago#13]
Hi guys, I think it is standard that a library should have an example folder with it, which works. So I think it would be really great if it will also have one.

The reason for asking a "Complete Working Example" is that I am nesting ReactTimeAgo component in Text component and it is consistently giving me errors of "Text string should be rendered with Text component", (I don't have to share any snip it cause I know my React brothers would already knew about this error) . If there would be a Complete Working Example in this git repo then I think everyone will be highly benefited from it. Thanks.

**Comment by catamphetamine** [comment]
> The reason for asking a "Complete Working Example" is that I am nesting ReactTimeAgo component in Text component and it is consistently giving me errors of "Text string should be rendered with Text component".

I guess you're using it with React Native that you have a `Text` component.
I didn't check this component in React Native, so it's not guaranteed.
