### ISSUE TITLE
Mocked Date object breaks module

### ISSUE THREAD

**Issue by nijk** [catamphetamine/react-time-ago#14]
Identical issue to this one on [javascript-time-ago](https://github.com/catamphetamine/javascript-time-ago/issues/22), except the [code that breaks the module is here](https://github.com/catamphetamine/react-time-ago/blob/master/source/ReactTimeAgo.js#L240).

**Comment by catamphetamine** [comment]
I went with a simpler solution:
https://github.com/catamphetamine/react-time-ago/blob/c9ec2622e1ac588cb593d39dce4ae93a19fb36fa/source/helpers/date.js

Released `react-time-ago@5.0.5`.

**Comment by nijk** [comment]
Unfortunately this does not fix the issue as the Date.constructor is still used for comparison

**Comment by catamphetamine** [comment]
Where exactly?

**Comment by catamphetamine** [comment]
I see, released `react-time-ago@5.0.6`.

**Comment by nijk** [comment]
Thanks for the speedy responses! The latest npm packages have solved my issue 👍
