### ISSUE TITLE
Invalid Time Value Error

### ISSUE THREAD

**Issue by pythoncreate** [catamphetamine/react-time-ago#16]
Not sure if there is something wrong with my date format, but i'm getting the Invalid Time Value Error.

In react this is my code

 <ReactTimeAgo
                date={new Date(
                  card.listingInfo && card.listingInfo[0].startTime
                ).toLocaleDateString()}
              />

my date data actually looks like this
2019-10-07T04:12:25.000Z 

but after running to localeDateString it looks like this

10/7/2019

any ideas?

**Comment by catamphetamine** [comment]
You're passing a string as a `date`.
Instead pass `card.listingInfo[0].startTime`.
