### ISSUE TITLE
Failed prop type: Invalid prop `date` supplied to `ReactTimeAgo`

### ISSUE THREAD

**Issue by michaeljarizala** [catamphetamine/react-time-ago#18]
I am suddenly getting this error and I am not sure what's causing it.

Btw, I am using redux and redux-persist for persisting my application states. Not sure if this is a direct cause to this ReactTimeAgo issue but I just think it might as I am converting my states to props, but not totally sure.

![image](https://user-images.githubusercontent.com/23579045/72200659-0a85ed80-3487-11ea-9d6d-d2b700b0256b.png)

![image](https://user-images.githubusercontent.com/23579045/72200672-3608d800-3487-11ea-9015-f246595ce3a5.png)

**Comment by catamphetamine** [comment]
Perhaps it converts `Date`s to `String`s when storing state.
Check `typeof date`.

**Comment by michaeljarizala** [comment]
Also, is there a way to show the full datetime if it is more than 1 day ago?

Example:
Writer publishes a new post. It will show `just now`, `1 minute ago`, `1 day ago`. But when it exceeds 1 day, it should show `Jan. 11, 2020  3:30 PM`

**Comment by michaeljarizala** [comment]
> Perhaps it converts `Date`s to `String`s when storing state.
> Check `typeof date`.

Noted, I will check on this...

Also, is there a way to show the full datetime if it is more than 1 day ago?

Example:
Writer publishes a new post. It will show `just now`, `1 minute ago`, `1 day ago`. But when it exceeds 1 day, it should show `Jan. 11, 2020  3:30 PM`

**Comment by catamphetamine** [comment]
> Also, is there a way to show the full datetime if it is more than 1 day ago?

Write custom style.
See the docs.

**Comment by owusuappiah** [comment]
Your answer to that question is not clear. The package is buggy

**Comment by catamphetamine** [comment]
@owusuappiah No, you is buggy.

**Comment by letowebdev** [comment]
still facing the same problem, how to solve this ?

**Comment by catamphetamine** [comment]
@letowebdev 

> how to solve this ?

Simply pass either a `Date` or a `Number` timestamp.
Most certainly you're passing a stringified date.

**Comment by mcbanderson** [comment]
Using `<ReactTimeAgo date={Date.parse(props.date)} locale="en-US"/>` instead of `<ReactTimeAgo date={props.date} locale="en-US"/>` removed the error for me.

FWIW the error seems spurious since the module was still handling the datetime string correctly, so it can either be safely ignored or removed from the code if anyone is willing to track it down.

**Comment by atomixim** [comment]
Any ideas on this? Using typescript and passing in a Date still returns this error

**Comment by chengdongXue** [comment]
@mcbanderson thanks it works for me

**Comment by gfxmoda** [comment]
<ReactTimeAgo date={new Date(article.post.publish_date)} />

**Comment by h4ck4life** [comment]
@gfxmoda your solution works. thanks!
