### ISSUE TITLE
Not able to dynamically apply locale

### ISSUE THREAD

**Issue by hbole** [catamphetamine/react-time-ago#20]
If i am trying to apply locale dynamically to locale, then it doesn't change

Here is my code: 
<ReactTimeAgo date={user.createdAt} locale={this.props.userSettings.showAppInHindi ? "hi" : "en"}/>

I have to refresh to see the correct format every time my condition in the above code changes.
Don't know what the issue is, please help.

**Comment by catamphetamine** [comment]
Try the latest version `6.x`
