### ISSUE TITLE
Is it possible to capitalise the formatted output?

### ISSUE THREAD

**Issue by mattrussell-sonocent** [catamphetamine/react-time-ago#9]
This is an awesome library, thanks!

Is there any way to capitalise the formatted output, e.g. "Just now" instead of "just now"?

**Comment by catamphetamine** [comment]
Use `:first-letter { text-transform: uppercase }` with `display: inline-block` or `display: block`.
https://stackoverflow.com/questions/5577364/make-the-first-character-uppercase-in-css

**Comment by mattrussell-sonocent** [comment]
Awesome, works a treat -- cheers!
